- name: Install Server Applications
  ansible.builtin.apt:
    pkg: 
      - linux-headers-amd64
    update_cache: yes
    state: present

- name: Install zfs from Backports
  ansible.builtin.apt:
    pkg: 
      - zfsutils-linux
    update_cache: yes
    state: present
    default_release: bookworm-backport