- name: Add Tailscale repository key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: present
  when: ansible_facts['lsb']['codename'] == "bookworm"

- name: Add Tailscale repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main"
    state: present
    filename: tailscale
  when: ansible_facts['lsb']['codename'] == "bookworm"


- name: Install Server Applications
  ansible.builtin.apt:
    pkg: 
      - linux-headers-amd64
      - dpkg-dev 
      - linux-headers-generic 
      - linux-image-generic
      - sanoid
      - tailscale
    update_cache: yes
    state: present

- name: Pin ZFS to backports
  ansible.builtin.copy:
    src: 90_zfs
    dest: /etc/apt/preferences.d/90_zfs
    owner: root
    group: root
    mode: '0644'

# TODO: Fix this had to run the apt-get command manually
#- name: Install zfs from Backports
#  ansible.builtin.command: "export DEBIAN_FRONTEND=noninteractive &&  apt-get install -t bookworm-backports zfs-dkms zfsutils-linux -y"


- name: Create docker-compose config directory
  ansible.builtin.file:
    path: /etc/docker-compose
    state: directory


- name: Copy docker-compose config
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /etc/docker-compose/docker-compose.yml
    owner: sam
    group: sam
    mode: '0644'

- name: Copy docker-compose envfile
  ansible.builtin.copy:
    src: .env
    dest: /etc/docker-compose/.env
    owner: sam
    group: sam
    mode: '0644'

- name: Add Tailscale repository key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: present
  when: ansible_facts['lsb']['codename'] == "bookworm"

- name: Add Tailscale repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main"
    state: present
    filename: tailscale
  when: ansible_facts['lsb']['codename'] == "bookworm"
