- name: Install Work Flatpak Applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - com.slack.Slack
    - https://downloads.1password.com/linux/flatpak/1Password.flatpakref

- name: Create work repo directory
  ansible.builtin.file:
    path: /home/sam/repos/madetech
    owner: sam
    group: sam
    state: directory