- name: Install Applications
  ansible.builtin.apt:
    pkg: 
      - git
      - vim
      - rsync
      - qemu-system
      - libvirt-clients
      - libvirt-daemon-system
      - virt-manager
    update_cache: yes
    state: present

- name: Append kvm group 
  ansible.builtin.user:
    name: sam
    groups: libvirt
    append: true